version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run -m pytest --junitxml=test-results/results.xml
            coverage report -m
            coverage html
      # Step 4: store test results
      - store_test_results:
          path: test-results