version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir -p test-results coverage_html
            mkdir -p important-coverage
            coverage run -m pytest --junitxml=test-results/results.xml
            coverage report -m
            coverage html -d coverage_html
            ls -al coverage_html
            # Copy only desired files to a clean artifact directory
            cp coverage_html/z_*Group_py.html important-coverage/
            cp coverage_html/z_*User_py.html important-coverage/
      # Step 4: store test results
      - store_test_results:
          path: test-results
      # Step 5: store useful artifacts for debugging
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_artifacts:
          path: coverage_html
          destination: coverage-report